FROM --platform=linux/amd64 public.ecr.aws/lambda/python:3.8

RUN yum update -y \
    && yum install -y amazon-linux-extras \
    && PYTHON=python2 amazon-linux-extras install epel \
    && yum -y install clamav clamd p7zip \
    && yum clean all \
    && pip3 install --no-cache-dir cffi awslambdaric boto3 requests aws-lambda-powertools \
    && ln -s /etc/freshclam.conf /tmp/freshclam.conf \
    && freshclam
COPY clamd.conf /etc/clamd.conf
COPY freshclam.conf /etc/freshclam.conf
COPY src/matcher.py /var/task/lambda.py
ENTRYPOINT [ "/var/lang/bin/python3", "-m", "awslambdaric" ]
CMD [ "lambda.matcher_lambda_handler" ]