FROM amazonlinux:2.0.20230504.1
RUN yum update -y && yum upgrade -y
# amazonlinux image needs shadow utils to add users
RUN yum -y install shadow-utils
RUN useradd --system dependenciesuser
COPY requirements-runtime.txt requirements.txt
COPY build-dependencies.sh .
ARG YARA_VERSION
RUN ./build-dependencies.sh $YARA_VERSION

USER dependenciesuser
