FROM amazonlinux
RUN dnf update -y && dnf upgrade -y
# amazonlinux image needs shadow utils to add users
RUN dnf -y install shadow-utils
RUN useradd --system dependenciesuser
COPY requirements-runtime.txt requirements.txt
COPY build-dependencies.sh .
ARG YARA_VERSION
RUN ./build-dependencies.sh $YARA_VERSION

USER dependenciesuser
