FROM alpine 
ARG YARA_VERSION
RUN addgroup --system yaragroup && adduser --system yarauser -G yaragroup
RUN apk update && apk add openssl-dev jansson-dev build-base libc-dev file-dev automake autoconf libtool flex git bison && \
            git clone --recursive --branch v$YARA_VERSION https://github.com/VirusTotal/yara.git && \
            cd yara && \
            ./bootstrap.sh && \
            ./configure && \
            make && \
            make install

RUN chown -R yarauser /yara
USER yarauser
