ARG ACCOUNT_NUMBER
ARG VERSION
FROM $ACCOUNT_NUMBER.dkr.ecr.eu-west-2.amazonaws.com/yara:$VERSION
RUN addgroup --system compilegroup && adduser --system compileuser -G compilegroup
WORKDIR /rules
COPY rule-sources /rules/rule-sources
COPY src/compile.py /rules/compile.py
RUN apk update && apk add py3-pip wget gcc python3-dev musl-dev git && \
            pip3 install yara-python && \
            cat rule-sources | xargs -n1 git clone && \
            wget https://raw.githubusercontent.com/Yara-Rules/rules/master/malware/MALW_Eicar.yar && \
            ./compile.py
RUN chown -R compileuser /rules

USER compileuser
