name: TDR Tag and pre deploy
on:
  push:
    branches:
      - master
      - move-to-github-actions
jobs:
  pre-deploy:
    uses: nationalarchives/tdr-github-actions/.github/workflows/lambda_build.yml@allow-non-jar-files
    with:
      repo-name: tdr-antivirus
      artifact-name: function
      artifact-file-type: zip
      artifact-path: lambda
      build-command: |
        docker build -f Dockerfile-yara --pull --no-cache --build-arg YARA_VERSION=$(cat yara-version.txt) -t yara .
        docker build -f Dockerfile-dependencies --pull --no-cache --build-arg YARA_VERSION=$(cat yara-version.txt) -t yara-dependencies .
        docker build -f Dockerfile-compile --no-cache -t yara-rules .
        docker run -itd --rm --name dependencies yara-dependencies
        docker cp dependencies:/lambda/dependencies.zip .
        docker run -itd --rm --name rules yara-rules
        mkdir lambda
        docker cp rules:/rules/output ./lambda
        unzip -q dependencies.zip -d ./lambda
        cp src/matcher.py ./lambda
        cd lambda
        zip -r9 function.zip .
        cd ..
    secrets:
      MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
  deploy:
    needs: pre-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: gh workflow run deploy.yml -f environment=intg -f to-deploy=${{ needs.pre-deploy.outputs.next-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
