name: TDR Tag and pre deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  pre-deploy:
    uses: nationalarchives/tdr-github-actions/.github/workflows/lambda_build.yml@main
    with:
      lambda-name: yara-av-v2
      repo-name: tdr-antivirus
      artifact-name: function
      artifact-file-type: zip
      artifact-path: lambda
      build-command: |        
        mkdir lambda        
        cp src/matcher.py ./lambda
        cd lambda
        zip -r9 function.zip .
        cd ..
    secrets:
      MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
      WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
      WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
      WIZ_PROJECT_ID: ${{ secrets.WIZ_PROJECT_TDR }}
  deploy:
    needs: pre-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - run: gh workflow run deploy.yml -f environment=intg -f to-deploy=${{ needs.pre-deploy.outputs.next-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
