name: TDR Run Lambda Tests
on:
  pull_request:
  push:
    branches-ignore:
      - master
      - release-*
permissions:
  id-token: write
  contents: write
jobs:
  test:
    uses: nationalarchives/tdr-github-actions/.github/workflows/tdr_test.yml@0deb3eafdf01ca41aac6cb81f3f0112a7a692b24 # v.0.0.33
    with:
      repo-name: tdr-antivirus
      test-command: |
        pip install -r requirements.txt
        pip install pyopenssl --upgrade
        python -m pytest
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
